version: 2.0

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "1d:c9:af:7c:4a:8d:3e:47:98:3c:be:42:98:a8:36:e5"
      - run: 
          name: Deploy application
          command: |
            ssh -oStrictHostKeyChecking=no -v ${SSH_USER}@${SERVER_IP} "cd ${SERVER_SIDE_DIR} && git pull origin master && ./deploy.sh ${SSH_USER_PWD}"

workflows:
  version: 2
  deployment:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
