# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  deploy-service:
    docker:
      - image: cibuilds/hugo:0.42.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SO:1d:c9:af:7c:4a:8d:3e:47:98:3c:be:42:98:a8:36:e5"
      - run: 
          name: Deploy application
          command: |
            ssh -oStrictHostKeyChecking=no -v $SSH_USER@$SERVER_IP "cd $SERVER_SIDE_DIR && git pull origin master && ./deploy.sh"

workflows:
  build-deploy:
    jobs:
      - deploy-service:
          name: Deploy LMS Server
          context: Production
          filters:
            branches:
              only: master